### ISSUE TITLE
Support for Grid Layout in SortableList Component

### ISSUE THREAD

**Issue by vivek20Eng** [rodrigodagostino/svelte-sortable-list#3]
` Branch : vivek20Eng:feature/grid-layout-support`
[Pull Request] (https://github.com/rodrigodagostino/svelte-sortable-list/pull/4)

## Description:
I am using the SortableList component from the @rodrigodagostino/svelte-sortable-list package and I am trying to arrange items in a grid format (It only support Horizontal or Vertical). However, the component does not seem to support the grid layout correctly when arranging items. The items should be draggable within a grid, and they should wrap to the next line if there's not enough space on the current line.

## Steps to Reproduce:
- Create a SortableList component with items.
- Apply CSS Grid to arrange items in a grid format.
- Enable drag-and-drop functionality within the grid.
- Support Touch Screen.

## Expected Behavior:
The items should be draggable within the grid, maintaining the grid structure and wrapping to the next line if there's not enough space.

## Actual Behavior:
The items are not maintaining the grid structure when dragged. The drag-and-drop functionality doesn't work as expected in the grid format.

Code Example:
```<script lang="ts">
    import { SortableList, sortItems, type SortableListProps } from '@rodrigodagostino/svelte-sortable-list';
    import '@rodrigodagostino/svelte-sortable-list/styles.css';

    let items: SortableListProps['items'] = [
        { id: 1, text: 'Item 1', image: 'https://via.placeholder.com/150' },
        { id: 2, text: 'Item 2', image: 'https://via.placeholder.com/150' },
        { id: 3, text: 'Item 3', image: 'https://via.placeholder.com/150' },
        { id: 4, text: 'Item 4', image: 'https://via.placeholder.com/150' },
    ];

    function handleSort(event: CustomEvent) {
        const { prevIndex, nextIndex } = event.detail;
        items = sortItems(items, prevIndex, nextIndex);
    }
</script>

<SortableList
    {items}
    direction="horizontal"
    on:sort={handleSort}
    class="album-grid"
>
    {#each items as item}
        <div class="card">
            <img src={item.image} alt={item.text} />
            <p>{item.text}</p>
        </div>
    {/each}
</SortableList>

<style>
    .album-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
        gap: 10px;
    }

    .card {
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }
</style>
```

**Comment by rishabp-alokin** [comment]
looking for this feature..
its needed

**Comment by rodrigodagostino** [comment]
Hi, @vivek20Eng! :)

Yes, as you’ve pointed out, currently there’s not support for grid layouts, but it is something I might consider adding in the future. Since it’s much more complicated than moving things around in a single axis and there are a lot of moving parts involved in the process, a feature like that would imply quite a lot of work, and, to be honest, I have my hands full with an important refactoring to improve the overall flexibility of the package.

But if you’d like to contribute to that feature, you are very welcome to do so :)

**Comment by vivek20Eng** [comment]
# Feature Request: Grid Layout Support for SortableList Component

## 📌 Current Situation
We are currently using the SortableList component from the @rodrigodagostino/svelte-sortable-list package in our project. While this component works well for horizontal and vertical layouts, we've identified a need for grid layout support to enhance our user interface.

## 💡 Requested Feature
We kindly request the addition of grid layout support to the SortableList component. This feature would allow items to be arranged and dragged within a grid structure, with automatic wrapping to the next line when space is limited.

## 📈 Use Case
In our application, we need to display and allow reordering of items in a grid format. This layout is crucial for efficiently using screen space and providing a more intuitive interface for our users, especially on devices with larger screens.

## 🚧 Current Limitations
1. The component currently only supports horizontal or vertical layouts.
2. Attempting to implement a grid layout using CSS results in unexpected behavior during drag-and-drop operations.
3. Items do not maintain their grid positions when dragged.
4. Adding icons to sortable items in a grid format causes issues with layout and drag-and-drop functionality.

## 🛠️ Proposed Solution
We suggest modifying the SortableList component to:
1. Add a new `layout` prop that accepts 'grid' as a value, in addition to 'horizontal' and 'vertical'.
2. Implement logic to handle item positioning and reordering within a grid structure.
3. Ensure that items wrap to the next line when there's insufficient space in the current row.
4. Maintain grid structure integrity during drag-and-drop operations.
5. Fix issues related to adding icons to sortable items when in grid format.

## 📝 Code Example
Here's a basic example of how we envision using the grid layout:

```svelte
<script>
import { SortableList } from '@rodrigodagostino/svelte-sortable-list';

let items = [
  { id: 1, content: 'Item 1' },
  { id: 2, content: 'Item 2' },
  // ... more items
];

function handleSort(event) {
  const { oldIndex, newIndex } = event.detail;
  // Handle reordering logic
}
</script>

<SortableList
  {items}
  layout="grid"
  on:sort={handleSort}
>
  {#each items as item (item.id)}
    <div class="grid-item">
      <span class="icon">🔧</span>
      {item.content}
    </div>
  {/each}
</SortableList>

<style>
.grid-item {
  width: 100px;
  height: 100px;
  margin: 5px;
  background-color: #f0f0f0;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}

.icon {
  margin-bottom: 5px;
}
</style>

**Comment by vivek20Eng** [comment]
## 📋 Additional Considerations
The grid layout should be responsive, adapting to different screen sizes.
Touch screen support should be maintained for mobile devices.
Accessibility features should be considered in the grid layout implementation.
## 🎯 Benefits
Implementing grid layout support would significantly enhance the flexibility and usability of the SortableList component, making it more versatile for various application designs and improving the overall user experience. Fixing the issue with icons in grid format will also ensure a smoother user experience.

We appreciate your consideration of this feature request and are happy to provide any additional information or clarification needed. Thank you for your excellent work on this component, and we look forward to the possibility of this enhancement.

**Comment by vivek20Eng** [comment]
## 🛠️ Current Issue

When sorting in grid format, items do not align correctly. This issue is being fixed.

**Comment by vivek20Eng** [comment]
![Uploading grid-layout-support2.png…]()

**Comment by vivek20Eng** [comment]
![grid-layout-support1](https://github.com/rodrigodagostino/svelte-sortable-list/assets/67886518/38b9d4c0-7a0d-46c9-9719-6d2fb1170c97)

**Comment by vivek20Eng** [comment]
![grid-layout-support2](https://github.com/rodrigodagostino/svelte-sortable-list/assets/67886518/e1b11ed5-0abe-4926-bf2c-1e59cfbde650)

**Comment by rodrigodagostino** [comment]
Due to inactivity, I will be closing this one for the time being.
Feel free to reopen it if you get back to work on it :)

**Comment by rodrigodagostino** [comment]
Hey, @vivek20Eng! :)

It’s been quite a while, but just in case you are still interested in the feature you requested, I wanted to let you know that since `v.0.13.0` there is now support for wrapping lists, which might cover your usecase :)

You can visit this [demo page](https://svelte-sortable-list.netlify.app/with-wrapping) to check it out.
